"""follpost img_path

Revision ID: 3cb61ba66270
Revises: c50aabbd817e
Create Date: 2022-06-24 15:27:58.528976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb61ba66270'
down_revision = 'c50aabbd817e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow__post', sa.Column('img_path', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follow__post', 'img_path')
    # ### end Alembic commands ###
